### ISSUE TITLE
大佬，前端开源吗？

### ISSUE THREAD

**Issue by alun1** [jinzhongjia/movie-getter#1]

**Comment by jinzhongjia** [comment]
可以，之前没开源的原因是因为前端写的太烂了🥺

**Comment by jinzhongjia** [comment]
前端前台：https://github.com/jinzhongjia/movie
前端后台：https://github.com/jinzhongjia/movie-admin

**Comment by alun1** [comment]
怎么会呢，总比我好吧。我想学习一下，谢谢大佬

**Comment by alun1** [comment]
大佬牛逼

**Comment by jinzhongjia** [comment]
新的前端前台：https://github.com/jinzhongjia/newMovie
多端自适应，黑夜模式适配，提高了交互效果，代码逻辑更清晰

**Comment by alun1** [comment]
66666
