### ISSUE TITLE
😂能不能编译arm64的镜像啊？

### ISSUE THREAD

**Issue by AndyNull** [jinzhongjia/movie-getter#16]
自己编译了下有问题，运行访问8000无响应///

**Comment by jinzhongjia** [comment]
尝试拉取latest试试，已经通过docker buildx跨cpu构建成功
![image](https://github.com/jinzhongjia/movie-getter/assets/41784264/8a88f0e6-9dea-41c8-b730-829a7c912fe5)

**Comment by jinzhongjia** [comment]
https://hub.docker.com/r/yunyizhiying/movie/tags
docker bub地址

**Comment by jinzhongjia** [comment]
由于我手头没有arm架构的机器，所以无法进行测试，如果运行成功烦请告知

**Comment by AndyNull** [comment]
CONTAINER ID   IMAGE                COMMAND        CREATED          STATUS          PORTS                                       NAMES
e0a3fd43c277   yunyizhiying/movie   "/app/movie"   16 seconds ago   Up 15 seconds   0.0.0.0:8000->8233/tcp, :::8000->8233/tcp   modest_edison

查询是arm64位镜像
"Architecture": "arm64",
        "Os": "linux",
        "Size": 25617047,

但是访问8000还是不行，端口已放行，表示正在使用

**Comment by jinzhongjia** [comment]
容器内log发上来看看

**Comment by jinzhongjia** [comment]
正常运行的话，最开始应该会打印以下信息：
```sh
Version:1.2.0
Status is OK, listen to http://127.0.0.1:8000
```
还有就是默认程序是只监听本地的8000端口，你需要将内部的127.0.0.1:8000映射出来

**Comment by AndyNull** [comment]
> 正常运行的话，最开始应该会打印以下信息：
> 
> ```shell
> Version:1.2.0
> Status is OK, listen to http://127.0.0.1:8000
> ```
> 
> 还有就是默认程序是只监听本地的8000端口，你需要将内部的127.0.0.1:8000映射出来

root@ubuntu:/home# docker logs e0a3fd43c277
Version:1.2.0
Status is OK, listen to http://127.0.0.1:8000
是的。。。

**Comment by jinzhongjia** [comment]
> > 正常运行的话，最开始应该会打印以下信息：
> > ```shell
> > Version:1.2.0
> > Status is OK, listen to http://127.0.0.1:8000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还有就是默认程序是只监听本地的8000端口，你需要将内部的127.0.0.1:8000映射出来
> 
> root@ubuntu:/home# docker logs e0a3fd43c277 Version:1.2.0 Status is OK, listen to http://127.0.0.1:8000 是的。。。

那就不是镜像的问题了，你端口映射不对

**Comment by jinzhongjia** [comment]
你是使用docker compose还是直接docker运行的容器

**Comment by AndyNull** [comment]
> 你是使用docker compose还是直接docker运行的容器

docker run 的

**Comment by jinzhongjia** [comment]
docker run后面加上参数 `-p 127.0.0.1:8000:8000 `

**Comment by jinzhongjia** [comment]
程序仅仅只监听容器内的localhost地址（需要对外映射），条件可以的话尽量使用docker compose部署，当然你可以自行修改它的监听地址，只要在容器中放入一个和程序同位置的`conf.ini`即可，具体配置可以参考仓库中的配置文件

**Comment by AndyNull** [comment]
> docker run后面加上参数 `-p 127.0.0.1:8000:8000 `

root@ubuntu:/home# docker run -d -p 127.0.0.1:8000:8000 -it yunyizhiying/movie
7dba9437fff0ada6cb5c5613fc08010766cb22551a4901d41f51a0a6063c197b
root@ubuntu:/home# docker ps
CONTAINER ID   IMAGE                COMMAND        CREATED          STATUS          PORTS                                NAMES
7dba9437fff0   yunyizhiying/movie   "/app/movie"   16 seconds ago   Up 16 seconds   127.0.0.1:8000->8000/tcp, 8233/tcp   intelligent_lamarr
root@ubuntu:/home# docker logs 7dba9437fff0
Version:1.2.0
Status is OK, listen to http://127.0.0.1:8000


我去试试docker compose

**Comment by jinzhongjia** [comment]
> > docker run后面加上参数 `-p 127.0.0.1:8000:8000 `
> 
> root@ubuntu:/home# docker run -d -p 127.0.0.1:8000:8000 -it yunyizhiying/movie 7dba9437fff0ada6cb5c5613fc08010766cb22551a4901d41f51a0a6063c197b root@ubuntu:/home# docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 7dba9437fff0 yunyizhiying/movie "/app/movie" 16 seconds ago Up 16 seconds 127.0.0.1:8000->8000/tcp, 8233/tcp intelligent_lamarr root@ubuntu:/home# docker logs 7dba9437fff0 Version:1.2.0 Status is OK, listen to http://127.0.0.1:8000
> 
> 我去试试docker compose

映射完成后，你就可以通过宿主机的8000端口访问容器内了，该端口被容器占用

**Comment by AndyNull** [comment]
这种映射也没有办法访问....

**Comment by jinzhongjia** [comment]
我本地测试一下，看看

**Comment by jinzhongjia** [comment]
貌似docker本身的映射规则有点问题，我本地测试也是无法访问，但是docker compose部署正常， 需要进一步进行测试，你可以先用docker compose，docker compose的部署文件已经在仓库中存放，可以直接使用

**Comment by AndyNull** [comment]
> 貌似docker本身的映射规则有点问题，我本地测试也是无法访问，但是docker compose部署正常， 需要进一步进行测试，你可以先用docker compose，docker compose的部署文件已经在仓库中存放，可以直接使用

好的，麻烦了哈
但是d-c会报错没有arm镜像。。
root@ubuntu:/home/movie-getter# docker-compose -p movie up -d
[+] Running 0/3
 ⠦ watchtower Pulling                                                         2.7s
 ⠦ db Pulling                                                                 2.7s
 ⠦ movie Pulling                                                              2.7s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by jinzhongjia** [comment]
只有v7架构的镜像，没有v8的

**Comment by AndyNull** [comment]
> 只有v7架构的镜像，没有v8的

哈哈，但是我是arm64的主机在请求，，，也返回的这个

**Comment by jinzhongjia** [comment]
等会我尝试看能不能构建v8的，暂时在排查映射问题

**Comment by AndyNull** [comment]
> 等会我尝试看能不能构建v8的，暂时在排查映射问题
哈哈，不着急，吃饭最大，晚点再弄吧

**Comment by jinzhongjia** [comment]
排查完成，docker compose不知道做了啥黑魔法，可能更改linux内核iptables的内容和普通的run不同，容器内需要监听`0.0.0.0:8000`，监听`localhost:8000`会导致docker run无法映射
还有个因素是我dockerfile的expose字段写错了。。。但只会影响docker run
一会我尝试构建一下v8的镜像

**Comment by AndyNull** [comment]
> 

😄，好的，麻烦了呢

**Comment by jinzhongjia** [comment]
构建完成v8版本了，现在docker run也没问题了

**Comment by AndyNull** [comment]
> 构建完成v8版本了，现在docker run也没问题了

刚测试，确实已经ok了，辛苦大佬了

**Comment by AndyNull** [comment]
哈哈，现在还不能对数据库进行操作哇？想清库没找到入口。。。

**Comment by jinzhongjia** [comment]
数据库没啥内容，前端的后台你删除就可以了，如果你非要操作数据库的话，没有用mysql，那就进容器内部，删除数据库文件，进去ls就可以看到，mysql的话你需要向外映射端口出来

**Comment by jinzhongjia** [comment]
实际上你在后台操作就完全够用了，不需要删库

**Comment by AndyNull** [comment]
> 实际上你在后台操作就完全够用了，不需要删库

行，谢谢了
