### ISSUE TITLE
问题解答

### ISSUE THREAD

**Issue by AndyNull** [jinzhongjia/movie-getter#17]
找到一个资源站还行，但是添加通用的api接口之后，程序没有采集结果
只有在演示站后台看到的几个接口，能正常采集数据

**Comment by jinzhongjia** [comment]
你需要找对应采集站的maccms的json接口，然后最好找到的是m3u8源，我没对资源站套壳播放器的采集地址做适配

**Comment by jinzhongjia** [comment]
资源站地址可以发上来看看

**Comment by AndyNull** [comment]
https://haiwaikan.com/

**Comment by AndyNull** [comment]
注意： 本站所有资源屏蔽中国大陆IP采集以及播放
通用采集josn接口：http://api.haiwaikan.com/v1/vod?ac=list
通用采集xml接口：https://haiwaikan.com/api.php/provide/vod/at/xml/?ac=list

**Comment by jinzhongjia** [comment]
这资源站魔改过采集接口，不是标准的mac cms格式

**Comment by jinzhongjia** [comment]
这个接口被魔改过一点，默认接口应该访问直接返回分类，但是此接口并不返回（而是返回错误信息），导致采集分类获取空数组

**Comment by AndyNull** [comment]
> 😂😂😂

**Comment by jinzhongjia** [comment]
应该可以通过调整请求参数兼容它这个问题，我倒是头一次遇到魔改接口的资源站

**Comment by jinzhongjia** [comment]
这魔改的还不少，影片时长这个必须存在的值被删除了，需要微调代码，下午我再搞吧

**Comment by AndyNull** [comment]
> 这魔改的还不少，影片时长这个必须存在的值被删除了，需要微调代码，下午我再搞吧

嗯，是感觉和其他的不太一样。

**Comment by jinzhongjia** [comment]
问题已修复

**Comment by jinzhongjia** [comment]
重新拉取镜像并部署就好

**Comment by AndyNull** [comment]
> 重新拉取镜像并部署就好

ok!感谢dxd

**Comment by AndyNull** [comment]
刚刚重新拉了，测试还是为空？

**Comment by jinzhongjia** [comment]
你地址是不是填后面的参数了，采集地址需要是:`https://api.haiwaikan.com/v1/vod`

**Comment by jinzhongjia** [comment]
其他参数在采集途中会添加，不需要关心

**Comment by AndyNull** [comment]
哟，果然复制了文档给的的api ...   已正常了

**Comment by AndyNull** [comment]
你的演示站gg了。。。

**Comment by jinzhongjia** [comment]
演示站是垃圾512M的小鸡，线路时不时抽风不用管

**Comment by AndyNull** [comment]
哈哈，这下又得采集一整天...

**Comment by jinzhongjia** [comment]
arm架构，你是部署在个人的软路由上吗

**Comment by AndyNull** [comment]
> arm架构，你是部署在个人的软路由上吗

没有，我弄在甲骨文上面的。。。

**Comment by AndyNull** [comment]
time="2023-08-18T08:01:42Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
time="2023-08-18T08:01:43Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
time="2023-08-18T08:01:44Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
time="2023-08-18T08:01:45Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
time="2023-08-18T08:01:45Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
time="2023-08-18T08:01:46Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"

后台抓不到数据，docker logs提示这个

**Comment by jinzhongjia** [comment]
> time="2023-08-18T08:01:42Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64" time="2023-08-18T08:01:43Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64" time="2023-08-18T08:01:44Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64" time="2023-08-18T08:01:45Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64" time="2023-08-18T08:01:45Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64" time="2023-08-18T08:01:46Z" level=error msg="some error occurred when get, err is interface conversion: interface {} is string, not float64"
> 
> 后台抓不到数据，docker logs提示这个

再往上找到上一条采集的影片名

**Comment by jinzhongjia** [comment]
把影片名发上来

**Comment by jinzhongjia** [comment]
还是这个采集站有的值直接缺省，它参数魔改的太多，我又不能把所有的值都设置为可选，那样的话错误数据也会被采集进来

**Comment by AndyNull** [comment]
> 还是这个采集站有的值直接缺省，它参数魔改的太多，我又不能把所有的值都设置为可选，那样的话错误数据也会被采集进来

哈哈，找不到了，logs刷满了，翻不上去了。。。

**Comment by AndyNull** [comment]
后台魔改源看到的最新的第一页第一个
56 | 柏拉图式性爱 | 松浦雅子 | 加贺美早纪,野波麻帆,石丸谦二郎,根岸季衣 |   | 如今的电影喜欢关注边缘人物

**Comment by jinzhongjia** [comment]
晚点我再修一下，你其实可以去找别的影视站采集

**Comment by AndyNull** [comment]
> 晚点我再修一下，你其实可以去找别的影视站采集

嗯，其他问题不大，主要是看这个源没有滚动广告，还比较高清

**Comment by jinzhongjia** [comment]
你看一下你对应源的下的影片最大id，把名字也复制过来

**Comment by jinzhongjia** [comment]
我都采集60多页了，也没遇到bug

**Comment by AndyNull** [comment]
> 我都采集60多页了，也没遇到bug
刚看了下后台，正常了，

**Comment by AndyNull** [comment]
有没有办法添加播放接口？这个魔改站的资源拒绝大陆直接访问，想在本地加个中转

**Comment by jinzhongjia** [comment]
拒绝大陆ip的话只能上反向代理吧，实现成本较高

**Comment by jinzhongjia** [comment]
或者用资源站提供的播放接口，但那样的话需要修改前端

**Comment by AndyNull** [comment]
哦哦~那就可以在后端修改一下播放器接口，这样就多样化了

**Comment by jinzhongjia** [comment]
不是的，一般这些播放接口其实是一个网页，然后里面是一个播放器组件，其他的采集器的解决方法都是通过，直接进行网页嵌套实现的，必须要前端进行一定的适配，但是我最初开发就没打算做这个适配，因为网页嵌套里面的内容是无法控制的

**Comment by AndyNull** [comment]
> 就没打算做这个

那确实是，那只有反向代理了？反向代理的话他这种资源站咋代理？感觉和普通的nginx反代不一样吧

**Comment by jinzhongjia** [comment]
需要流式代理，会占用cpu，而且成本过高

**Comment by AndyNull** [comment]
哦哦，啧，那恼火

**Comment by AndyNull** [comment]
我刚刚尝试了直接go run main.go运行，这个样子的话我修改播放前端那一部分源码是在src那里面吗？我尝试了修改但是并不生效....

**Comment by jinzhongjia** [comment]
dist文件夹下才是，dist/dist.go用来内嵌前端打包出来的东西
src只是存放clone下来的前端源码

**Comment by AndyNull** [comment]
> dist文件夹下才是，dist/dist.go用来内嵌前端打包出来的东西 src只是存放clone下来的前端源码

好叻，看了一脸懵，对vue这个不太熟，等会空了再来看看怎么修改下前端播放

**Comment by jinzhongjia** [comment]
编译的步骤是，先git下前端的源码（前台和后台），然后执行编译，然后将编译好的前端送入dist目录，再开始编译整个采集器
具体看makefile

**Comment by AndyNull** [comment]
> 编译的步骤是，先git下前端的源码（前台和后台），然后执行编译，然后将编译好的前端送入dist目录，再开始编译整个采集器 具体看makefile

好的。那其实我修改源码之后，直接编译就行了吧...

**Comment by jinzhongjia** [comment]
对

**Comment by AndyNull** [comment]
> 对

哈哈，尝试了dp播放器嵌套，结果就是在播放页无法播放，但是F12看视频连接确实在前面加了自己定义的dp接口，双击打开能单独播放。
但是嵌套在页面就加载不出来。。。

**Comment by AndyNull** [comment]
请教个问题啊，就是我现在反向代理叻资源连接，但是访问的时候它的切片ts是另外一个cdn的连接，，导致现在用网站播放反代视频资源的时候，会报切片资源403错误，没有 CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
这种怎么操作一波呢？

**Comment by jinzhongjia** [comment]
触发跨域问题，你需要修改请求响应的头部

**Comment by AndyNull** [comment]
> 触发跨域问题，你需要修改请求响应的头部

刚看了下，还是因为锁定大陆ip导致的，爱国一下就不存在跨域问题，那么这个东西，笑死，咋个才能搞啊？网站内部挂代理？

**Comment by jinzhongjia** [comment]
不知道喽
