### ISSUE TITLE
安装以后后台进不去

### ISSUE THREAD

**Issue by siamoe** [jinzhongjia/movie-getter#19]
安装以后后台进不去，编译的不行，docker的也不行..下载编译好的文件也是进后台没反应

**Comment by jinzhongjia** [comment]
docker是用compose还是docker run 部署的

编译的话拉main分支，需要有nodejs和pnpm，make文件需要拉去前端（前台后台）源码

release的是旧的，不是最新分支编译

**Comment by siamoe** [comment]
docker-compose

**Comment by jinzhongjia** [comment]
docker log看看

**Comment by jinzhongjia** [comment]
不要watchtower和mysql的log

**Comment by siamoe** [comment]
看了错误，是数据库一直链接错误....用的是docker-compose -p movie up -d

**Comment by jinzhongjia** [comment]
动过compose文件？

**Comment by siamoe** [comment]
没有，git 下来以后进目录直接docker-compose -p movie up -d

**Comment by jinzhongjia** [comment]
> 没有，git 下来以后进目录直接docker-compose -p movie up -d

问题无法复现，本地刚刚完成测试，拉取镜像通过`docker compose`部署，一切正常

**Comment by siamoe** [comment]
我换一台机器在试试

**Comment by siamoe** [comment]
还是一样的错误，怎么联系你，我把VPS的信息发给你

**Comment by jinzhongjia** [comment]
> 还是一样的错误，怎么联系你，我把VPS的信息发给你

即时通讯方式（qq，telegram均可）发送到[mail@nvimer.org](mailto:mail@nvimer.org)，注明来意就行
