### ISSUE TITLE
修改密码后注销再次登陆密码输入被限制在8位

### ISSUE THREAD

**Issue by Lumysia** [jinzhongjia/movie-getter#3]
## 修改密码后注销再次登陆密码输入被限制在8位

https://github.com/jinzhongjia/movie-admin/blob/83ff29b6ea133c4e9a011e0266e724d145e24305/src/components/Login.vue#L35-L43

> Line41出现此限制，请问这个是有其他考虑嘛？

**Comment by jinzhongjia** [comment]
后台页面是半年前的了，这个应该是我当时去文档复制组件失误带进来的，没有考虑，可以直接删除
这个后台管理打算重构的，逻辑混乱+没有自适应+旧代码

**Comment by Lumysia** [comment]
ok，感谢您的答复。
早就在找采集站点的替代品都准备自己写了但是发现这个，真的十分感谢。

**Comment by jinzhongjia** [comment]
> ok，感谢您的答复。
> 早就在找采集站点的替代品都准备自己写了但是发现这个，真的十分感谢。

如果愿意参加开发的话，欢迎pr😁
