### ISSUE TITLE
大佬这个全局资源采集 能不能加一个自定义资源采集

### ISSUE THREAD

**Issue by TIUCSIB** [jinzhongjia/movie-getter#4]
比如采集动漫。只采集自己平时爱看的几部。太多了，每次都需要去搜索来看。

**Comment by jinzhongjia** [comment]
> 比如采集动漫。只采集自己平时爱看的几部。太多了，每次都需要去搜索来看。

由于采集的逻辑是爬取提供的json,这个功能没法实现，只有采集后才可以看到有什么动漫

**Comment by TIUCSIB** [comment]
> > 比如采集动漫。只采集自己平时爱看的几部。太多了，每次都需要去搜索来看。
> 
> 由于采集的逻辑是爬取提供的json,这个功能没法实现，只有采集后才可以看到有什么动漫

好吧。原来如此 谢谢大佬解答
