### ISSUE TITLE
请问我通过docker安装之后打不开

### ISSUE THREAD

**Issue by alonedogboy** [jinzhongjia/movie-getter#5]
我通过docker安装，然后域名绑定了IP，访问域名打不开，请问怎么回事
![image](https://user-images.githubusercontent.com/61310130/215777939-5046a11a-05bb-4985-b74c-023b6682dfe7.png)

**Comment by jinzhongjia** [comment]
看容器的日志

```
docker log 容器id
```

**Comment by alonedogboy** [comment]
> 

docker build --network=host -t yunyizhiying/movie .

执行这条命令后没有创建容器
![image](https://user-images.githubusercontent.com/61310130/215780434-f2b7e46c-d436-4eea-849e-b264bf602892.png)
![image](https://user-images.githubusercontent.com/61310130/215780533-cd870381-ad48-4b73-8513-dbf447f7f9a6.png)

**Comment by jinzhongjia** [comment]
```sh
docker build --network=host -t yunyizhiying/movie .
```
该指令作用并非创建容器，而是构建容器镜像

你如果部署的话建议使用docker-compose,他是docker容器的一个批量部署工具

本仓库的根目录已经配备了docker-compose文件
