### ISSUE TITLE
本地使用了vpn还是一直下载不了一些https://proxy.golang.org的包，有解决方案嘛

### ISSUE THREAD

**Issue by oumaharuki** [jinzhongjia/movie-getter#7]

**Comment by jinzhongjia** [comment]
如果是vpn的话，请开启全局代理模式
或者使用七牛云提供的[goproxy](https://goproxy.cn/)

**Comment by oumaharuki** [comment]
![image](https://user-images.githubusercontent.com/29711725/230076032-cd966d91-7258-4a85-8c2b-60fb426862bf.png)
大佬这个是什么错误可以解释一下么

**Comment by jinzhongjia** [comment]
> ![image](https://user-images.githubusercontent.com/29711725/230076032-cd966d91-7258-4a85-8c2b-60fb426862bf.png) 大佬这个是什么错误可以解释一下么

由于sqlite依赖cgo，它不是静态链接，使用的是动态链接，所以你在运行时需要对应的动态链接库，看起来应该是c环境缺失？（我只能作出此推测，因为我自己在本地运行测试并没遇到该问题）

**Comment by oumaharuki** [comment]
大佬，demo页面打不开了

**Comment by jinzhongjia** [comment]
> 大佬，demo页面打不开了

没问题，demo的服务器是垃圾512M的小鸡，还是国外机器，线路不好，偶尔会打不开

**Comment by oumaharuki** [comment]
大佬，我golang已经忘完了，想问问是不是没做增量采集和指定视频采集。如果我想做这两个接口，应该怎么搞。

**Comment by jinzhongjia** [comment]
> 大佬，我golang已经忘完了，想问问是不是没做增量采集和指定视频采集。如果我想做这两个接口，应该怎么搞。

增量采集做了，逻辑是每个采集源会单开一个groutine进行采集，指定视频采集是指采集某一个视频吗？还是某个视频类别
类别的话已经内置了，但是指定采集单个视频这个没法实现，因为先采集影片后才知道是否存在你要找的影片的，在你搜索的时候影片就已经存在了

**Comment by jinzhongjia** [comment]
> 大佬，我golang已经忘完了，想问问是不是没做增量采集和指定视频采集。如果我想做这两个接口，应该怎么搞。

具体可以参考这里：

https://github.com/jinzhongjia/movie-getter/blob/ef662e8c2f9184541161b4c2fff0490c8c01fdce/getter/getDaily.go#L12-L37

**Comment by oumaharuki** [comment]
有一些视频是每周指定时间更新的，比如斗破苍穹动漫，每周日更新，我已经采集在数据库了，我是想加一个按钮，就是点击这个就更新斗破新的视频。我还想加一个接口就是点击了就更新指定采集源增量的部分，我看现在现有的应该是全量更新吧，就是那个重新采集的按钮。还有这边增量更新的时间间隔是多久呢，因为我发现有些视频是很久都不会更新。看到有一个定时任务是四个小时更新的，应该不是这个吧，因为四个小时早过去了。

**Comment by jinzhongjia** [comment]
> 有一些视频是每周指定时间更新的，比如斗破苍穹动漫，每周日更新，我已经采集在数据库了，我是想加一个按钮，就是点击这个就更新斗破新的视频。我还想加一个接口就是点击了就更新指定采集源增量的部分，我看现在现有的应该是全量更新吧，就是那个重新采集的按钮。还有这边增量更新的时间间隔是多久呢，因为我发现有些视频是很久都不会更新。看到有一个定时任务是四个小时更新的，应该不是这个吧，因为四个小时早过去了。

有记录，优先全量，全量采集完成后定时进行增量采集（默认4小时一次），至于你说的有些视频很久不更新，大概率是采集站没有更新，因为设置每次是直接获取之前的采集间隔更新的资源，默认是不会出现遗漏的

**Comment by jinzhongjia** [comment]
至于你说的某个视频前台被点击后后台就更新，这个没有对应的api，你需要实现对外暴漏的api，当前前台触发后后台进行更新，注意进行防抖操作（防止有人获取到接口后对系统进行攻击）

**Comment by jinzhongjia** [comment]
有兴趣开发前端后台吗，我一直想重构前端的后台（页面中有些api没加，缺失，需要使用post工具主动触发api），但缺乏设计思路

**Comment by oumaharuki** [comment]
我现在主java和python的，golang已经好多年没用了，做前端还差不多，我是有打算重新前端页面的

**Comment by oumaharuki** [comment]
如果不嫌弃我可以加进来一起写写后端，就是可以比较忙的时候就做不了，我是想等我重学了golang改一下代码，加上uv pv统计功能。

**Comment by oumaharuki** [comment]
还有一些定制的功能，比如，新番配置功能。

**Comment by jinzhongjia** [comment]
可以，你可以直接fork然后提pr

我刚才看了一下你的fork内容，前端前台源码：https://github.com/jinzhongjia/newMovie
然后里面的`docker-compose.yml`只是模板

**Comment by oumaharuki** [comment]
OK
