### ISSUE TITLE
资源采集的两个疑问

### ISSUE THREAD

**Issue by libsgh** [jinzhongjia/movie-getter#9]
1. 多个采集站是怎样进行资源去重的呢，有没有好的去重方式，根据名称?最终媒资信息保留一份，播放地址存多份？
2. 每个资源站的资源分类是不一样的，比如A站叫电视剧，B站叫连续剧，有没有好的分类统一方式呢？

**Comment by jinzhongjia** [comment]
1. 资源去重这个是通病，因为各个采集站的影片名都不同，所以很难处理，我没有加去重处理（理想的方案是使用ai进行影片名对比，但是成本太高）
2. 资源站分类不同的处理方法是存在一个本地的资源分类，然后采集分类绑定到本地的资源分类上，前端所显示的都是本地由管理员创建的本地资源分类，这是通用方案

**Comment by libsgh** [comment]
> 1. 资源去重这个是通病，因为各个采集站的影片名都不同，所以很难处理，我没有加去重处理（理想的方案是使用ai进行影片名对比，但是成本太高）
> 2. 资源站分类不同的处理方法是存在一个本地的资源分类，然后采集分类绑定到本地的资源分类上，前端所显示的都是本地由管理员创建的本地资源分类，这是通用方案

大佬回复好快，感谢解答，没看过苹果CMS的代码，第二点和我想的差不多
第一点用ai会很慢吧，很多影视站都有去重，应该是有插件，如果不去重的话，节目集合会成倍增加，前端展示也不友好

**Comment by jinzhongjia** [comment]
> > 1. 资源去重这个是通病，因为各个采集站的影片名都不同，所以很难处理，我没有加去重处理（理想的方案是使用ai进行影片名对比，但是成本太高）
> > 2. 资源站分类不同的处理方法是存在一个本地的资源分类，然后采集分类绑定到本地的资源分类上，前端所显示的都是本地由管理员创建的本地资源分类，这是通用方案
> 
> 大佬回复好快，感谢解答，没看过苹果CMS的代码，第二点和我想的差不多
> 第一点用ai会很慢吧，很多影视站都有去重，应该是有插件，如果不去重的话，节目集合会成倍增加，前端展示也不友好

去重这个方案我也没细考虑过，这个采集器算是闲暇做的玩具，后面有时间打算重构一部分代码
